### ISSUE TITLE
Problems with MyStrom Switches V1 since 1.1.x version (in Homeassistant)

### ISSUE THREAD

**Issue by l00mi** [fabaff/python-mystrom#15]
Since the last update I get the error below in my Homeassistant log file on start-up. The switches are then also shown as `Entity not available: switch.music`, curiously enough though, if triggered through a script they work!

```
2020-05-17 17:15:45 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 445, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 608, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/usr/src/homeassistant/homeassistant/components/mystrom/switch.py", line 58, in is_on
    return bool(self.data["relay"])
KeyError: 'relay'
```

Thank you for the nice work on this integration, I use it in HA for quite some time know without any troubles.

**Comment by fabaff** [comment]
Was fixed with https://github.com/home-assistant/core/pull/34079

**Comment by l00mi** [comment]
Sorry, I missed that one. Thank you.
